export const MS_WELCOME = 'CHAO MUNG BAN DEN VOI SHOPPING ONLINE';
export const MS_ADD_SUCCESS = 'MUA THANH CONG';
export const MS_EMPTY = 'CHUA CO SAN PHAM TRONG GIO HANG';
export const MS_DELETE = 'XOA THANH CONG';
